/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param loanId 
 * @param amount 
 * @param totalAmount 
 * @param interest 
 * @param dateTime 
 * @param numberDate 
 * @param total 
 */


data class BasicLoanInformation (

    @SerializedName("loanId")
    val loanId: java.util.UUID? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("totalAmount")
    val totalAmount: kotlin.Double? = null,

    @SerializedName("interest")
    val interest: kotlin.Double? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("numberDate")
    val numberDate: kotlin.Int? = null,

    @SerializedName("total")
    val total: kotlin.Double? = null

) {


}

