/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.Loan
import org.confiape.loan.models.TagBorrowerClient

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param changeBy 
 * @param changeDate 
 * @param isDeleted 
 * @param avatar 
 * @param background 
 * @param name 
 * @param dni 
 * @param dniPath 
 * @param email 
 * @param phoneNumber 
 * @param title 
 * @param company 
 * @param birthday 
 * @param address 
 * @param notes 
 * @param status 
 * @param loans 
 * @param tagBorrowerClients 
 */


data class BorrowerClient (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("changeBy")
    val changeBy: java.util.UUID? = null,

    @SerializedName("changeDate")
    val changeDate: java.time.OffsetDateTime? = null,

    @SerializedName("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @SerializedName("avatar")
    val avatar: kotlin.String? = null,

    @SerializedName("background")
    val background: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("dni")
    val dni: kotlin.String? = null,

    @SerializedName("dniPath")
    val dniPath: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("company")
    val company: kotlin.String? = null,

    @SerializedName("birthday")
    val birthday: java.time.OffsetDateTime? = null,

    @SerializedName("address")
    val address: kotlin.String? = null,

    @SerializedName("notes")
    val notes: kotlin.String? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("loans")
    val loans: kotlin.collections.List<Loan>? = null,

    @SerializedName("tagBorrowerClients")
    val tagBorrowerClients: kotlin.collections.List<TagBorrowerClient>? = null

) {


}

