/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param iso 
 * @param name 
 * @param code 
 * @param flagImagePos 
 */


data class CountryDto (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("iso")
    val iso: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("code")
    val code: kotlin.String? = null,

    @SerializedName("flagImagePos")
    val flagImagePos: kotlin.String? = null

) {


}

