/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.DayOfWeek

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param year 
 * @param month 
 * @param day 
 * @param dayOfWeek 
 * @param dayOfYear 
 * @param dayNumber 
 */


data class DateOnly (

    @SerializedName("year")
    val year: kotlin.Int? = null,

    @SerializedName("month")
    val month: kotlin.Int? = null,

    @SerializedName("day")
    val day: kotlin.Int? = null,

    @SerializedName("dayOfWeek")
    val dayOfWeek: DayOfWeek? = null,

    @SerializedName("dayOfYear")
    val dayOfYear: kotlin.Int? = null,

    @SerializedName("dayNumber")
    val dayNumber: kotlin.Int? = null

) {


}

