/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param x 
 * @param y 
 */


data class LoansByMonthDto (

    @SerializedName("x")
    val x: java.time.OffsetDateTime? = null,

    @SerializedName("y")
    val y: kotlin.Int? = null

) {


}

