/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.BorrowerClient
import org.confiape.loan.models.LoanType
import org.confiape.loan.models.Payment
import org.confiape.loan.models.PointDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param changeBy 
 * @param changeDate 
 * @param isDeleted 
 * @param amount 
 * @param interest 
 * @param dateTime 
 * @param numberDate 
 * @param loanType 
 * @param suggestedDays 
 * @param borrowerClientId 
 * @param borrowerClient 
 * @param payments 
 * @param currentLocation 
 */


data class Loan (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("changeBy")
    val changeBy: java.util.UUID? = null,

    @SerializedName("changeDate")
    val changeDate: java.time.OffsetDateTime? = null,

    @SerializedName("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("interest")
    val interest: kotlin.Double? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("numberDate")
    val numberDate: kotlin.Int? = null,

    @SerializedName("loanType")
    val loanType: LoanType? = null,

    @SerializedName("suggestedDays")
    val suggestedDays: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("borrowerClientId")
    val borrowerClientId: java.util.UUID? = null,

    @SerializedName("borrowerClient")
    val borrowerClient: BorrowerClient? = null,

    @SerializedName("payments")
    val payments: kotlin.collections.List<Payment>? = null,

    @SerializedName("currentLocation")
    val currentLocation: PointDto? = null

) {


}

