/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param loanId 
 * @param name 
 * @param title 
 * @param amount 
 * @param interest 
 * @param tag 
 * @param dateTime 
 */


data class LoanAndDate (

    @SerializedName("loanId")
    val loanId: java.util.UUID? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("interest")
    val interest: kotlin.Double? = null,

    @SerializedName("tag")
    val tag: kotlin.String? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null

) {


}

