/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.LoansByMonthDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param `data` 
 */


data class LoansByMonthDtoMetadata (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("data")
    val `data`: kotlin.collections.List<LoansByMonthDto>? = null

) {


}

