/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.PersonDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param accessToken 
 * @param tokenType 
 */


data class LoginResponse (

    @SerializedName("user")
    val user: PersonDto? = null,

    @SerializedName("accessToken")
    val accessToken: kotlin.String? = null,

    @SerializedName("tokenType")
    val tokenType: kotlin.String? = null

) {


}

