/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.Loan
import org.confiape.loan.models.PointDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param changeBy 
 * @param changeDate 
 * @param isDeleted 
 * @param dateTime 
 * @param amount 
 * @param location 
 * @param loanId 
 * @param loan 
 */


data class Payment (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("changeBy")
    val changeBy: java.util.UUID? = null,

    @SerializedName("changeDate")
    val changeDate: java.time.OffsetDateTime? = null,

    @SerializedName("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("location")
    val location: PointDto? = null,

    @SerializedName("loanId")
    val loanId: java.util.UUID? = null,

    @SerializedName("loan")
    val loan: Loan? = null

) {


}

