/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param latitude 
 * @param longitude 
 */


data class PointDto (

    @SerializedName("latitude")
    val latitude: kotlin.Double? = null,

    @SerializedName("longitude")
    val longitude: kotlin.Double? = null

) {


}

