/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.DateOnly

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param loanDate 
 * @param amount 
 * @param payment 
 */


data class ReportPaymentsDto (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("loanDate")
    val loanDate: DateOnly? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("payment")
    val payment: kotlin.Double? = null

) {


}

