/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.DateOnly
import org.confiape.loan.models.ReportPaymentsDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 * @param totalPayment 
 * @param detailsDto 
 */


data class ReportPaymentByDayDto (

    @SerializedName("dateTime")
    val dateTime: DateOnly? = null,

    @SerializedName("totalPayment")
    val totalPayment: kotlin.Double? = null,

    @SerializedName("detailsDto")
    val detailsDto: kotlin.collections.List<ReportPaymentsDto>? = null

) {


}

