/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.ReportPaymentByLoanDetailsDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param dni 
 * @param tags 
 * @param dateTime 
 * @param amount 
 * @param interest 
 * @param totalAmount 
 * @param totalPayment 
 * @param isComplete 
 * @param detailedDtos 
 */


data class ReportPaymentByLoanDto (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("dni")
    val dni: kotlin.String? = null,

    @SerializedName("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("interest")
    val interest: kotlin.Double? = null,

    @SerializedName("totalAmount")
    val totalAmount: kotlin.Double? = null,

    @SerializedName("totalPayment")
    val totalPayment: kotlin.Double? = null,

    @SerializedName("isComplete")
    val isComplete: kotlin.Boolean? = null,

    @SerializedName("detailedDtos")
    val detailedDtos: kotlin.collections.List<ReportPaymentByLoanDetailsDto>? = null

) {


}

