/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.SimplePayments

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param amount 
 * @param interest 
 * @param dateTime 
 * @param numberDate 
 * @param borrowerClientId 
 * @param totalAmount 
 * @param totalPayment 
 * @param payments 
 */


data class SimpleLoanDtoAndPayments (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("amount")
    val amount: kotlin.Double? = null,

    @SerializedName("interest")
    val interest: kotlin.Double? = null,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("numberDate")
    val numberDate: kotlin.Int? = null,

    @SerializedName("borrowerClientId")
    val borrowerClientId: java.util.UUID? = null,

    @SerializedName("totalAmount")
    val totalAmount: kotlin.Double? = null,

    @SerializedName("totalPayment")
    val totalPayment: kotlin.Double? = null,

    @SerializedName("payments")
    val payments: kotlin.collections.List<SimplePayments>? = null

) {


}

