/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.BorrowerClient
import org.confiape.loan.models.Tag

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param changeBy 
 * @param changeDate 
 * @param isDeleted 
 * @param tagId 
 * @param borrowerClientId 
 * @param tag 
 * @param borrowerClient 
 */


data class TagBorrowerClient (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("changeBy")
    val changeBy: java.util.UUID? = null,

    @SerializedName("changeDate")
    val changeDate: java.time.OffsetDateTime? = null,

    @SerializedName("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @SerializedName("tagId")
    val tagId: java.util.UUID? = null,

    @SerializedName("borrowerClientId")
    val borrowerClientId: java.util.UUID? = null,

    @SerializedName("tag")
    val tag: Tag? = null,

    @SerializedName("borrowerClient")
    val borrowerClient: BorrowerClient? = null

) {


}

