/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models

import org.confiape.loan.models.UpdateBorrowerClientDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param borrowerClientDto 
 * @param tagIdList 
 */


data class UpdateBorrowerClientDtoNewBorrowerClientDto (

    @SerializedName("borrowerClientDto")
    val borrowerClientDto: UpdateBorrowerClientDto? = null,

    @SerializedName("tagIdList")
    val tagIdList: kotlin.collections.List<java.util.UUID>? = null

) {


}

