/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confiape.loan.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 */


data class UserDto (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

